### PR TITLE
Dependency updates 

### PR DESCRIPTION
**Pull request by mxmason**
## Description

- Updates dependencies to latest stable versions. no major semver bumps
- Adds Husky, lint-staged, and prettier,
- Adds the npm lockfile 
- Deletes the yarn lockfile
- gitignores `.eslintcache`, which is new in eslintv4 and used to make diffs between eslint runs faster. it's only needed on the dev machine itself

## Type of Changes

|   | Type                                        |
|---|----------------------------|
|   | :bug: Bug fix                           |
|   | :sparkles: New feature           |
|   | :hammer: Refactoring            |
|   | :100: Add tests                       |
|✓| :link: Update dependencies  |
|   | :scroll: Docs                            |
|✓| :broom: Chore                        |

### CODE REVIEW

**Review by segdeha — APPROVED** [review]
Looks good. What is Husky?

**Comment by mxmason** [comment]
@segdeha it makes it a lot easier to write scripts that run at stages of a commit, e.g., do X tasks before a commit is made, do Y tasks post commit. 

I added it reflexively since it was in TCL12’s repo, but then realized they never used it. Happy to omit 😅

**Comment by segdeha** [comment]
> @segdeha it makes it a lot easier to write scripts that run at stages of a commit, e.g., do X tasks before a commit is made, do Y tasks post commit.
> 
> I added it reflexively since it was in TCL12’s repo, but then realized they never used it. Happy to omit 😅

Yeah, if you didn't have a specific use in mind, let's keep things simple. Thanks!

**Comment by mxmason** [comment]
Okay, @segdeha, I knew I was forgetting something. Husky is `prettier`'s preferred tool for pre-commit linting. The changes I just pushed will do the following: 
- Enforce the `jsx-plugin-a11y` rules through `eslint`. This makes eslint throw a handful of automatable a11y checks. For instance, it will throw an error if devs add a role of `button` to something and do not add the expected event handlers.
- Enforce lint rules in the precommit stage, preventing commits if eslint has unresolved errors
- run prettier during precommit, so files look consistent on github without requiring the developer to run prettier on their machine

I've also just moved a handful of dependencies to `devDependencies` so they're not needlessly installed when the app is deployed.

I'm ok with scaling back any of this if it's too opinionated, but I wanted to put it out there.

**Review by segdeha — APPROVED** [review]
Love this! We should talk with our team about the decisions here. I am a bit surprised Husky doesn’t just come along as a prettier dependency 🤔 In any case, approved!

**Pull request merged**
